# Generated by Django 4.1.1 on 2022-09-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0005_user_secret2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mode",
            field=models.IntegerField(
                choices=[(1, "user"), (2, "administrator")], default=1, null=True
            ),
        ),
    ]
