# Generated by Django 4.1.1 on 2022-09-15 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0006_alter_user_mode"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="secret",
            new_name="access_secret",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="secret2",
            new_name="refresh_secret",
        ),
    ]
