# Generated by Django 4.1.1 on 2022-09-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0007_rename_secret_user_access_secret_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=250),
        ),
    ]
